version: "3.8"
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    volumes:
      - ./data/kafka:/var/run/docker.sock
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
  producer:
    container_name: producer
    build: ./producer
    ports:
      - 8080:8080
    volumes:
      - ./producer:/app
    environment:
      - PORT=8080
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - KAFKA_TOPIC=topic1
    depends_on:
      - kafka
  consumer:
    container_name: consumer
    build: ./consumer
    ports:
      - 8081:8081
    volumes:
      - ./consumer:/app
    environment:
      - PORT=8081
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - KAFKA_TOPIC=topic1
      - MONGO_URL=mongodb://mongo:27017/consumer
    depends_on:
      - kafka
      - mongo
  # frontend:
  #   container_name: frontend
  #   build: ./frontend
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
